apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-example
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: secret-demo
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: secret/secret