apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: registry-1.docker.io/azamatkomaev
    path: .
    targetRevision: 0.28.0
    helm:
      releaseName: vault
      values: |
        global:
          enabled: true
          tlsDisable: false
        server:
          extraEnvironmentVars:
            VAULT_CACERT: /vault/userconfig/vault-server-cacerts/root_ca.crt
          volumes:
            - name: userconfig-vault-server-tls
              secret:
                defaultMode: 420
                secretName: vault-tls
            - name: userconfig-vault-server-tls-cacerts
              secret:
                defaultMode: 420
                secretName: vault-tls-cacerts

          volumeMounts:
            - mountPath: /vault/userconfig/vault-server-tls
              name: userconfig-vault-server-tls
              readOnly: true
            - mountPath: /vault/userconfig/vault-server-cacerts
              name: userconfig-vault-server-tls-cacerts
              readOnly: true
          service:
            type: NodePort
            nodePort: 31232

          ha:
            enabled: true
            replicas: 1
            raft:
              enabled: true
              config: |
                ui = true

                listener "tcp" {
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
                  tls_key_file  = "/vault/userconfig/vault-server-tls/tls.key"
                }

                storage "raft" {
                  path = "/vault/data"
                }

                service_registration "kubernetes" {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true

  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
